# Generated by Django 2.2.9 on 2021-09-30 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210914_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(choices=[('humor', 'humor'), ('animals', 'animals'), ('auto', 'auto'), ('books', 'books'), ('serials', 'serials'), ('biograthy', 'biograthy')], unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(choices=[('Юмор', 'Юмор'), ('Животные', 'Животные'), ('Авто', 'Авто'), ('Книги', 'Книги'), ('Сериалы', 'Сериалы'), ('Биография', 'Биография')], max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Группа, к которой будет относиться пост', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.Group'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Текст нового поста'),
        ),
    ]
